inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'csv/**/*'
    - 'xml/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/symplectic/elements/csv/transform_job.rb'
    - 'cli.thor'

Metrics/BlockLength:
  Exclude:
    - 'spec/lib/symplectic/elements/xml/users_spec.rb'
    - 'spec/lib/symplectic/elements/csv/transform_job_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/symplectic/elements/xml/user.rb'
    - 'cli.thor'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/symplectic/elements/csv/transform_job.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/symplectic/elements/csv/transform_job.rb'
    - 'lib/symplectic/elements/user_feed.rb'
    - 'cli.thor'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/symplectic/elements/csv/transform_job.rb'

Rails/Blank:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/lib/symplectic/elements/csv/transform_job_spec.rb'
