inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'csv/**/*'
    - 'xml/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/symplectic/elements/csv/transform_job.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/lib/symplectic/elements/xml/users_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/symplectic/elements/xml/user.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/symplectic/elements/csv/transform_job.rb'
